version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  commands:
    - python -m pip install .
    - python -m pip install --no-cache-dir -r docs/requirements.txt
    - python -m sphinx -E -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
   configuration: docs/conf.py